# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Build and deploy JAR app to Azure Web App - demolinfunapp

on:
  push:
    branches:
      - develop
    paths:
      - 'java-code/**'
      - 'pom.xml'
      - '.github/workflows/main_demotestspringboot.yml'

env:
  AZURE_FUNCTIONAPP_NAME: demofunlinapp # set this to your function app name on Azure
  PACKAGE_DIRECTORY: './java-app/**/*.jar' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Unit Testing
        run: mvn test
        
      - name: Build with Maven and Run SonarCloud analysis
        run: mvn clean verify sonar:sonar
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Rename JAR file
      #   run: mv target/*.jar target/my-app.jar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'     

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Run Azure Functions Action
        id: deploy-to-functionapp
        uses:  Azure/functions-action@v1
        with:
          app-name: 'demolinfunapp'
          slot-name: 'Production'
          package: '${{ env.PACKAGE_DIRECTORY }}'
          respect-pom-xml: true
          publish-profile: ${{ secrets.PUBLISHPROFILE }}
