name: Build and deploy JAR app to Azure Function App - demofunlinapp

on:
  push:
    branches:
      - develop
    paths:
      - 'java-code/**'
      - 'pom.xml'
      - '.github/workflows/main_demotestspringboot.yml'

env:
  AZURE_FUNCTIONAPP_NAME: demofunlinapp # set this to your function app name on Azure
  JAVA_VERSION: '17' # set this to the java version to use

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Unit Testing
        run: mvn test
        
      - name: Build with Maven and Run SonarCloud analysis
        run: mvn clean verify sonar:sonar
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Rename JAR file
        run: mv target/*.jar target/my-app.jar

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Upload JAR to Azure Storage
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --name my-app.jar \
            --file target/my-app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Download JAR from Azure Storage
        run: |
          az storage blob download \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --name my-app.jar \
            --file my-app.jar

      - name: Zip the JAR file
        run: zip -j my-app.zip my-app.jar

      - name: Run Azure Functions Action
        id: deploy-to-functionapp
        uses: Azure/functions-action@v1
        with:
          app-name: 'demofunlinapp'
          package: 'my-app.zip'
          respect-pom-xml: true
          publish-profile: ${{ secrets.PUBLISHPROFILE }}
